server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ticketa-redis
      port: 6379
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@ipKeyResolver}"
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth

        - id: event-catalog-service
          uri: lb://event-catalog-service
          predicates:
            - Path=/api/v1/events/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 50
                key-resolver: "#{@userKeyResolver}"
            - name: CircuitBreaker
              args:
                name: eventServiceCircuitBreaker
                fallbackUri: forward:/fallback/events


resilience4j:
  circuitbreaker:
    instances:
      authServiceCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
      eventServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      authServiceCircuitBreaker:
        timeoutDuration: 2s
      eventServiceCircuitBreaker:
        timeoutDuration: 3s
jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://ticketa-discovery:8761/eureka/