spring:
  application:
    name: notification-ticket-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"